//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BixcieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bb_person
    {
        public int person_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_initial { get; set; }
        public string suffix { get; set; }
        public string prefix { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string preferred_name { get; set; }
        public Nullable<int> add_user { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<int> chg_user { get; set; }
        public Nullable<System.DateTime> chg_date { get; set; }
    }
}
