//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BixcieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bb_person_type
    {
        public int id { get; set; }
        public int person_id { get; set; }
        public int type_id { get; set; }
    }
}
