//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BixcieDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bb_type
    {
        public int type_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> add_user { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<int> chg_user { get; set; }
        public Nullable<System.DateTime> chg_date { get; set; }
    }
}
