//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BixcieDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BixcieBoutiqueDBEntities : DbContext
    {
        public BixcieBoutiqueDBEntities()
            : base("name=BixcieBoutiqueDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bb_person> bb_person { get; set; }
        public virtual DbSet<bb_person_type> bb_person_type { get; set; }
        public virtual DbSet<bb_type> bb_type { get; set; }
    }
}
